### ISSUE TITLE
ERROR: The certificate of ‘database.radioid.net’ is not trusted.

### ISSUE THREAD

**Issue by f5swb** [kencormack/pistar-lastqso#8]
hello, since yesterday I 've this problem with the fnDMR_DOWNLOAD_USERCSV()

sudo wget --show-progress --progress=bar:force:noscroll https://database.radioid.net/static/user.csv
--2022-08-13 15:23:03--  https://database.radioid.net/static/user.csv
Resolving database.radioid.net (database.radioid.net)... 172.105.2.72
Connecting to database.radioid.net (database.radioid.net)|172.105.2.72|:443... connected.
ERROR: The certificate of ‘database.radioid.net’ is not trusted.
ERROR: The certificate of ‘database.radioid.net’ doesn't have a known issuer.

If you have any idea it seems to be from the debian certificate ?

best 73's !

**Comment by f5swb** [comment]
you must add --no-check-certificate after the wget command ... there are still errors but we can download the last file 
 sudo wget --no-check-certificate https://database.radioid.net/static/user.csv
--2022-08-13 16:05:44--  https://database.radioid.net/static/user.csv
Resolving database.radioid.net (database.radioid.net)... 172.105.2.72
Connecting to database.radioid.net (database.radioid.net)|172.105.2.72|:443... connected.
WARNING: The certificate of ‘database.radioid.net’ is not trusted.
WARNING: The certificate of ‘database.radioid.net’ doesn't have a known issuer.
HTTP request sent, awaiting response... 200 OK
Length: 12776769 (12M) [text/csv]
Saving to: ‘user.csv’

user.csv                                100%[============================================================================>]  12.18M  4.34MB/s    in 2.8s

2022-08-13 16:05:48 (4.34 MB/s) - ‘user.csv’ saved [12776769/12776769]

**Comment by kencormack** [comment]
The issue is that the site's certificate, whether it has expired, or their certificate authority is having an issue, or whatever.  The error isn't a problem with the pistar-lastqso script, per se... it is something the folks at radioid.net will have to fix.

You've suggested a temporary change you can make to the script, to cause the script to ignore that error, though it is not a change I plan to deploy as a permanent change to pistar-lastqso.  Certificates are meant to ensure you are getting what you believe you are getting, from the people from whom you believe you are getting it.  Ignoring the certificate opens the script up to accepting a bogus file from a compromised server.

It should be noted, however, that making such a change to the script, such as suggested, will cause a "git pull" to error, the next time you attempt to update pistar-lastqso.  (Git will have detected that your file has been modified, and will refuse to overwrite it with an updated version.  To correct, you'll need to run "git reset --hard origin" before attempting a "git pull", to update the script.  [See the "Updating" portion of the README for details.](https://github.com/kencormack/pistar-lastqso#updating)

Until the radioid.net people square away their certificat problem, you can update the file manually with the following command, before launching pistar-lastqso...
`sudo wget --no-check-certificate -q --show-progress --progress=bar:force:noscroll https://database.radioid.net/static/user.csv -O /usr/local/etc/user.csv`

**Comment by kencormack** [comment]
I just re-tried retrieving the file with the script's "-c|--csv" option.  I no longer see the error.  It appears they've fixed their certificate issue.

**Comment by f5swb** [comment]
Many thanks ken ! Congrats again for your good job 👍

Envoyé de mon iPhone

Le 13 août 2022 à 18:21, Ken Cormack ***@***.***> a écrit :

﻿

I just re-tried retrieving the file with the script's "-c|--csv" option. I no longer see the error. It appears they've fixed their certificate issue.
